version: '3.8'

services:
    php-fpm:
        container_name: cc_php
        build:
            context: .docker/php-fpm
            dockerfile: Dockerfile
        tty: true
        ports:
            - '9000:9000'
        volumes:
            - ./source:/var/www/app
            - ./.logs/php:/var/log/php
        environment:
            - PROVIDER_API_ACCESS_KEY=${PROVIDER_API_ACCESS_KEY}
